name: Michael Nichols
description: Front-end development and design
url: http://mumptastic.com
markdown: redcarpet
highlighter: pygments.rb # or rouge or null
redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data", "html", "javascript"]
twitter_username: mumptastic
github_username:  mumptastic
gems: [jekyll-paginate]
paginate: 5
permalink: pretty